# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'firstui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import utils


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(812, 490)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.tervcimLayout = QtWidgets.QHBoxLayout()
        self.tervcimLayout.setSpacing(15)
        self.tervcimLayout.setObjectName("tervcimLayout")
        self.tervcimLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.tervcimLabel.setFont(font)
        self.tervcimLabel.setObjectName("tervcimLabel")
        self.tervcimLayout.addWidget(self.tervcimLabel)
        self.tervcimTextInput = QtWidgets.QTextEdit(self.centralwidget)
        self.tervcimTextInput.setMaximumSize(QtCore.QSize(16777215, 101))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.tervcimTextInput.setFont(font)
        self.tervcimTextInput.setObjectName("tervcimTextInput")
        self.tervcimLayout.addWidget(self.tervcimTextInput)
        self.gridLayout.addLayout(self.tervcimLayout, 0, 0, 1, 1)
        self.iktatoLayout = QtWidgets.QHBoxLayout()
        self.iktatoLayout.setObjectName("iktatoLayout")
        self.iktatoszamLabel = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.iktatoszamLabel.setFont(font)
        self.iktatoszamLabel.setObjectName("iktatoszamLabel")
        self.iktatoLayout.addWidget(self.iktatoszamLabel)
        self.iktatoszamInput = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.iktatoszamInput.sizePolicy().hasHeightForWidth())
        self.iktatoszamInput.setSizePolicy(sizePolicy)
        self.iktatoszamInput.setMinimumSize(QtCore.QSize(200, 33))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.iktatoszamInput.setFont(font)
        self.iktatoszamInput.setText("")
        self.iktatoszamInput.setObjectName("iktatoszamInput")
        self.iktatoLayout.addWidget(self.iktatoszamInput)
        self.tipusBox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tipusBox.sizePolicy().hasHeightForWidth())
        self.tipusBox.setSizePolicy(sizePolicy)
        self.tipusBox.setMinimumSize(QtCore.QSize(240, 33))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.tipusBox.setFont(font)
        self.tipusBox.setObjectName("tipusBox")
        self.tipusBox.addItem("")
        self.tipusBox.addItem("")
        self.tipusBox.addItem("")
        self.iktatoLayout.addWidget(self.tipusBox)
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.addButton.sizePolicy().hasHeightForWidth())
        self.addButton.setSizePolicy(sizePolicy)
        self.addButton.setMinimumSize(QtCore.QSize(180, 33))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.iktatoLayout.addWidget(self.addButton)
        self.gridLayout.addLayout(self.iktatoLayout, 1, 0, 1, 1)
        self.tableViewLayout = QtWidgets.QHBoxLayout()
        self.tableViewLayout.setObjectName("tableViewLayout")
        self.lemondoTable = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lemondoTable.sizePolicy().hasHeightForWidth())

        self.lemondoTable.setSizePolicy(sizePolicy)
        self.lemondoTable.setMinimumSize(QtCore.QSize(682, 0))
        self.lemondoTable.setMaximumSize(QtCore.QSize(682, 16777215))
        self.lemondoTable.setStyleSheet("font: 18pt \"Arial\";")
        self.lemondoTable.setObjectName("lemondoTable")
        self.lemondoTable.setColumnCount(0)
        self.lemondoTable.setRowCount(0)

        # Táblanézet formázása
        self.lemondoTable.setHorizontalHeaderLabels(['Iktatószám', 'Tervcím', 'Engedélytípus'])
        self.lemondoTable.setColumnCount(3)
        self.lemondoTable.setColumnWidth(0,218)
        self.lemondoTable.setColumnWidth(1,246)
        self.lemondoTable.setColumnWidth(2,218)
        

        self.tableViewLayout.addWidget(self.lemondoTable)
        self.tableviewButtonLayout = QtWidgets.QVBoxLayout()
        self.tableviewButtonLayout.setObjectName("tableviewButtonLayout")
        self.modositButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modositButton.sizePolicy().hasHeightForWidth())
        self.modositButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.modositButton.setFont(font)
        self.modositButton.setObjectName("modositButton")
        self.tableviewButtonLayout.addWidget(self.modositButton)
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deleteButton.sizePolicy().hasHeightForWidth())
        self.deleteButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.deleteButton.setFont(font)
        self.deleteButton.setObjectName("deleteButton")
        self.tableviewButtonLayout.addWidget(self.deleteButton)
        self.tableViewLayout.addLayout(self.tableviewButtonLayout)
        self.gridLayout.addLayout(self.tableViewLayout, 2, 0, 1, 1)
        self.letrehozLayout = QtWidgets.QVBoxLayout()
        self.letrehozLayout.setObjectName("letrehozLayout")
        self.folderButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folderButton.sizePolicy().hasHeightForWidth())
        self.folderButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.folderButton.setFont(font)
        self.folderButton.setObjectName("folderButton")
        self.letrehozLayout.addWidget(self.folderButton)
        self.createButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.createButton.sizePolicy().hasHeightForWidth())
        self.createButton.setSizePolicy(sizePolicy)
        self.createButton.setMinimumSize(QtCore.QSize(200, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(18)
        self.createButton.setFont(font)
        self.createButton.setObjectName("createButton")
        self.letrehozLayout.addWidget(self.createButton)
        self.gridLayout.addLayout(self.letrehozLayout, 3, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        self.addButton.clicked.connect(self.add_row)
        self.folderButton.clicked.connect(self.pick_folder)

        self.deleteButton.clicked.connect(self.delete_row)
        



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tervcimLabel.setText(_translate("MainWindow", "Tervcím:"))
        self.tervcimTextInput.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.iktatoszamLabel.setText(_translate("MainWindow", "Iktatószám:"))
        self.tipusBox.setItemText(0, _translate("MainWindow", "Használatbavételi"))
        self.tipusBox.setItemText(1, _translate("MainWindow", "Építési"))
        self.tipusBox.setItemText(2, _translate("MainWindow", "Bontási"))
        self.addButton.setText(_translate("MainWindow", "Hozzáad"))
        self.modositButton.setText(_translate("MainWindow", "Módosít"))
        self.deleteButton.setText(_translate("MainWindow", "Törlés"))
        self.folderButton.setText(_translate("MainWindow", "Mappa választása"))
        self.createButton.setText(_translate("MainWindow", "Létrehoz"))

    def add_row(self):
        
        count = self.lemondoTable.rowCount()
        self.lemondoTable.insertRow(count)
        self.lemondoTable.setItem(count, 0, QtWidgets.QTableWidgetItem(self.iktatoszamInput.text()))
        self.lemondoTable.setItem(count, 1, QtWidgets.QTableWidgetItem(self.tervcimTextInput.toPlainText()))
        self.lemondoTable.setItem(count, 2, QtWidgets.QTableWidgetItem(self.tipusBox.currentText()))
        
        # inputok frissítése
        self.iktatoszamInput.setText('')
        self.tervcimTextInput.setText('')

    def pick_folder(self):
        folder_path = QtWidgets.QFileDialog.getExistingDirectory(self,"Select folder")
        utils.save_folder = folder_path


    def delete_row(self):
        print(utils.save_folder)